version: '3'
services:
  web:
    image: cs353hw4app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cs353hw4db
    ports:
      - "3307:3306"
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
